"""baseline current schema

Create the current application schema for a fresh database.
For an existing database that already matches the SQLAlchemy models,
use `alembic stamp head` instead of running this revision.

Revision ID: f7d09ee5b728
Revises: 
Create Date: 2026-04-23 10:06:12.187435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d09ee5b728'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_company_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_nipt', sa.String(length=64), nullable=False),
    sa.Column('materialized_at', sa.DateTime(), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('source_structured_record_ids', sa.JSON(), nullable=True),
    sa.Column('latest_winner_name', sa.Text(), nullable=True),
    sa.Column('first_procurement_date', sa.Date(), nullable=True),
    sa.Column('last_procurement_date', sa.Date(), nullable=True),
    sa.Column('total_budget_limit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_winner_value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cancelled_procurement_count', sa.Integer(), nullable=False),
    sa.Column('suspended_procurement_count', sa.Integer(), nullable=False),
    sa.Column('distinct_contracting_authority_count', sa.Integer(), nullable=False),
    sa.Column('distinct_procedure_type_count', sa.Integer(), nullable=False),
    sa.Column('distinct_contract_type_count', sa.Integer(), nullable=False),
    sa.Column('has_small_value_procedures', sa.Boolean(), nullable=False),
    sa.Column('has_open_local_procedures', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_company_features')),
    sa.UniqueConstraint('company_nipt', name='uq_app_company_feature_company_nipt')
    )
    with op.batch_alter_table('app_company_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_company_features_company_nipt'), ['company_nipt'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_company_features_first_procurement_date'), ['first_procurement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_company_features_last_procurement_date'), ['last_procurement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_company_features_materialized_at'), ['materialized_at'], unique=False)

    op.create_table('joined_company_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_nipt', sa.String(length=64), nullable=False),
    sa.Column('materialized_at', sa.DateTime(), nullable=False),
    sa.Column('app_source_row_count', sa.Integer(), nullable=False),
    sa.Column('app_source_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('app_structured_record_ids', sa.JSON(), nullable=True),
    sa.Column('qkb_source_row_count', sa.Integer(), nullable=False),
    sa.Column('qkb_source_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('qkb_structured_record_ids', sa.JSON(), nullable=True),
    sa.Column('exact_join_match', sa.Boolean(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=True),
    sa.Column('legal_form', sa.String(length=255), nullable=True),
    sa.Column('subject_status', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('first_procurement_date', sa.Date(), nullable=True),
    sa.Column('last_procurement_date', sa.Date(), nullable=True),
    sa.Column('company_age_days_at_first_procurement', sa.Integer(), nullable=True),
    sa.Column('company_age_days_at_last_procurement', sa.Integer(), nullable=True),
    sa.Column('total_budget_limit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_winner_value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cancelled_procurement_count', sa.Integer(), nullable=False),
    sa.Column('suspended_procurement_count', sa.Integer(), nullable=False),
    sa.Column('has_red_flags', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_joined_company_features')),
    sa.UniqueConstraint('company_nipt', name='uq_joined_company_feature_company_nipt')
    )
    with op.batch_alter_table('joined_company_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_joined_company_features_company_nipt'), ['company_nipt'], unique=False)
        batch_op.create_index(batch_op.f('ix_joined_company_features_first_procurement_date'), ['first_procurement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_joined_company_features_last_procurement_date'), ['last_procurement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_joined_company_features_materialized_at'), ['materialized_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_joined_company_features_registration_date'), ['registration_date'], unique=False)

    op.create_table('qkb_company_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_nipt', sa.String(length=64), nullable=False),
    sa.Column('materialized_at', sa.DateTime(), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('source_structured_record_ids', sa.JSON(), nullable=True),
    sa.Column('business_name', sa.Text(), nullable=True),
    sa.Column('trade_name', sa.Text(), nullable=True),
    sa.Column('legal_form', sa.String(length=255), nullable=True),
    sa.Column('subject_status', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('registration_year', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('has_red_flags', sa.Boolean(), nullable=True),
    sa.Column('has_activity_text', sa.Boolean(), nullable=False),
    sa.Column('has_ownership_text', sa.Boolean(), nullable=False),
    sa.Column('search_window_start', sa.Date(), nullable=True),
    sa.Column('search_window_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qkb_company_features')),
    sa.UniqueConstraint('company_nipt', name='uq_qkb_company_feature_company_nipt')
    )
    with op.batch_alter_table('qkb_company_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qkb_company_features_company_nipt'), ['company_nipt'], unique=False)
        batch_op.create_index(batch_op.f('ix_qkb_company_features_materialized_at'), ['materialized_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qkb_company_features_registration_date'), ['registration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_qkb_company_features_registration_year'), ['registration_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_qkb_company_features_search_window_end'), ['search_window_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_qkb_company_features_search_window_start'), ['search_window_start'], unique=False)

    op.create_table('raw_fetches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetch_kind', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_fetches'))
    )
    with op.batch_alter_table('raw_fetches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_fetches_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_fetches_fetch_kind'), ['fetch_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_fetches_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_fetches_source_name'), ['source_name'], unique=False)

    op.create_table('structured_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structured_records')),
    sa.UniqueConstraint('source_name', 'record_type', 'external_key', name='uq_source_record_external_key')
    )
    with op.batch_alter_table('structured_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structured_records_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_records_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_records_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_records_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_records_source_name'), ['source_name'], unique=False)

    op.create_table('normalized_app_export_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structured_record_id', sa.Integer(), nullable=False),
    sa.Column('raw_fetch_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_external_key', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('materialized_at', sa.DateTime(), nullable=False),
    sa.Column('export_year', sa.Integer(), nullable=False),
    sa.Column('row_ordinal', sa.Integer(), nullable=False),
    sa.Column('procurement_reference', sa.String(length=255), nullable=True),
    sa.Column('contracting_authority', sa.Text(), nullable=True),
    sa.Column('procurement_subject', sa.Text(), nullable=True),
    sa.Column('procedure_type', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('budget_limit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('winner_name', sa.Text(), nullable=True),
    sa.Column('winner_nipt', sa.String(length=64), nullable=True),
    sa.Column('winner_value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cpv_codes', sa.Text(), nullable=True),
    sa.Column('source_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['raw_fetch_id'], ['raw_fetches.id'], name=op.f('fk_normalized_app_export_rows_raw_fetch_id_raw_fetches')),
    sa.ForeignKeyConstraint(['structured_record_id'], ['structured_records.id'], name=op.f('fk_normalized_app_export_rows_structured_record_id_structured_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_app_export_rows')),
    sa.UniqueConstraint('structured_record_id', 'row_ordinal', name='uq_normalized_app_export_snapshot_row')
    )
    with op.batch_alter_table('normalized_app_export_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_export_year'), ['export_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_materialized_at'), ['materialized_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_procurement_reference'), ['procurement_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_publication_date'), ['publication_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_raw_fetch_id'), ['raw_fetch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_snapshot_external_key'), ['snapshot_external_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_structured_record_id'), ['structured_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_app_export_rows_winner_nipt'), ['winner_nipt'], unique=False)

    op.create_table('normalized_qkb_search_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structured_record_id', sa.Integer(), nullable=False),
    sa.Column('raw_fetch_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_external_key', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('materialized_at', sa.DateTime(), nullable=False),
    sa.Column('result_ordinal', sa.Integer(), nullable=False),
    sa.Column('search_nipt', sa.String(length=64), nullable=True),
    sa.Column('search_date_from', sa.Date(), nullable=True),
    sa.Column('search_date_to', sa.Date(), nullable=True),
    sa.Column('business_nipt', sa.String(length=64), nullable=True),
    sa.Column('business_name', sa.Text(), nullable=True),
    sa.Column('trade_name', sa.Text(), nullable=True),
    sa.Column('legal_form', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('ownership_text', sa.String(length=255), nullable=True),
    sa.Column('subject_status', sa.String(length=255), nullable=True),
    sa.Column('subject_type', sa.String(length=255), nullable=True),
    sa.Column('activity_text', sa.Text(), nullable=True),
    sa.Column('administrators_text', sa.Text(), nullable=True),
    sa.Column('has_red_flags', sa.Boolean(), nullable=True),
    sa.Column('source_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['raw_fetch_id'], ['raw_fetches.id'], name=op.f('fk_normalized_qkb_search_rows_raw_fetch_id_raw_fetches')),
    sa.ForeignKeyConstraint(['structured_record_id'], ['structured_records.id'], name=op.f('fk_normalized_qkb_search_rows_structured_record_id_structured_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_qkb_search_rows')),
    sa.UniqueConstraint('structured_record_id', 'result_ordinal', name='uq_normalized_qkb_search_snapshot_result')
    )
    with op.batch_alter_table('normalized_qkb_search_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_business_nipt'), ['business_nipt'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_materialized_at'), ['materialized_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_raw_fetch_id'), ['raw_fetch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_registration_date'), ['registration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_search_date_from'), ['search_date_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_search_date_to'), ['search_date_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_search_nipt'), ['search_nipt'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_snapshot_external_key'), ['snapshot_external_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_qkb_search_rows_structured_record_id'), ['structured_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_qkb_search_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_structured_record_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_source_name'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_snapshot_external_key'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_search_nipt'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_search_date_to'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_search_date_from'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_registration_date'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_raw_fetch_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_materialized_at'))
        batch_op.drop_index(batch_op.f('ix_normalized_qkb_search_rows_business_nipt'))

    op.drop_table('normalized_qkb_search_rows')
    with op.batch_alter_table('normalized_app_export_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_winner_nipt'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_structured_record_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_source_name'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_snapshot_external_key'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_raw_fetch_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_publication_date'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_procurement_reference'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_materialized_at'))
        batch_op.drop_index(batch_op.f('ix_normalized_app_export_rows_export_year'))

    op.drop_table('normalized_app_export_rows')
    with op.batch_alter_table('structured_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_structured_records_source_name'))
        batch_op.drop_index(batch_op.f('ix_structured_records_record_type'))
        batch_op.drop_index(batch_op.f('ix_structured_records_published_at'))
        batch_op.drop_index(batch_op.f('ix_structured_records_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_structured_records_external_id'))
        batch_op.drop_index(batch_op.f('ix_structured_records_content_hash'))

    op.drop_table('structured_records')
    with op.batch_alter_table('raw_fetches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_fetches_source_name'))
        batch_op.drop_index(batch_op.f('ix_raw_fetches_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_raw_fetches_fetch_kind'))
        batch_op.drop_index(batch_op.f('ix_raw_fetches_content_hash'))

    op.drop_table('raw_fetches')
    with op.batch_alter_table('qkb_company_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qkb_company_features_search_window_start'))
        batch_op.drop_index(batch_op.f('ix_qkb_company_features_search_window_end'))
        batch_op.drop_index(batch_op.f('ix_qkb_company_features_registration_year'))
        batch_op.drop_index(batch_op.f('ix_qkb_company_features_registration_date'))
        batch_op.drop_index(batch_op.f('ix_qkb_company_features_materialized_at'))
        batch_op.drop_index(batch_op.f('ix_qkb_company_features_company_nipt'))

    op.drop_table('qkb_company_features')
    with op.batch_alter_table('joined_company_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_joined_company_features_registration_date'))
        batch_op.drop_index(batch_op.f('ix_joined_company_features_materialized_at'))
        batch_op.drop_index(batch_op.f('ix_joined_company_features_last_procurement_date'))
        batch_op.drop_index(batch_op.f('ix_joined_company_features_first_procurement_date'))
        batch_op.drop_index(batch_op.f('ix_joined_company_features_company_nipt'))

    op.drop_table('joined_company_features')
    with op.batch_alter_table('app_company_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_company_features_materialized_at'))
        batch_op.drop_index(batch_op.f('ix_app_company_features_last_procurement_date'))
        batch_op.drop_index(batch_op.f('ix_app_company_features_first_procurement_date'))
        batch_op.drop_index(batch_op.f('ix_app_company_features_company_nipt'))

    op.drop_table('app_company_features')
    # ### end Alembic commands ###
