"""add raw fetch corruption quarantine

Revision ID: aaef71721e11
Revises: f7d09ee5b728
Create Date: 2026-04-23 12:54:44.409957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaef71721e11'
down_revision: Union[str, None] = 'f7d09ee5b728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_fetches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_corrupted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('corruption_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_raw_fetches_is_corrupted'), ['is_corrupted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_fetches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_fetches_is_corrupted'))
        batch_op.drop_column('corruption_reason')
        batch_op.drop_column('is_corrupted')

    # ### end Alembic commands ###
